### ISSUE TITLE
New Production Deployment Meta Issue

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#199]
This issue is to track all of the sub-issues and tasks needed to upgrade the deployment for the SPDX online tools.

- [x] Containerize the SPDX online tools (issue #188)
- [x] Add environment variable for redis host (Issue #193)
- [x] Update docker configuration to use the redis host environment variables (Issue #207)
- [x] Decide on deployment Google Cloud or Amazon AWS (Issue #194)
- [x] Setup sandbox production environment (Issue #197)
- [x] Assign fixed IP address
- [x] Add SSL (Issue #189)
- [x] Decide on / document new deployment architecture (Issue #198)
- [x] Complete configuration for the new deployment architecture
- [x] Test new deployment
- [x] Assign a more permanent URL (Issue #196)
- [x] Backup the original production database, restore on the new production environment
- [x] Remove redirect to the old production machine in the nginx configuration file
- [x] Replace the current SPDX tools website with a redirect to the new URL
- [x] Update the configuration for the Oauth callback URL to point to `https://tools.spdx.org` (issue #221)

**Comment by goneall** [comment]
@kmehant @Ugtan @rtgdk I created a new issues label "Production" and this meta-issue to track the steps to create a new and improved deployment infrastructure.  Let me know if I missed anything.  Feel free to comment in the individual issues.

**Comment by goneall** [comment]
Sandbox has been created and can be accessed at http://13.57.134.254/

**Comment by rnjudge** [comment]
I saw that there was a PR merged to containerize the SPDX tools but can't find any corresponding documentation on how users would actually create/utilize the SPDX tools container. Does this exist somewhere?

**Comment by goneall** [comment]
> I saw that there was a PR merged to containerize the SPDX tools but can't find any corresponding documentation on how users would actually create/utilize the SPDX tools container. Does this exist somewhere?

The original PR has some instructions in the PR itself: https://github.com/spdx/spdx-online-tools/pull/188

I wrote up the production deployment instructions for the containers for the 2 deployment configurations I tested with the containers:

* [Kubernetes based deployement](https://github.com/spdx/spdx-online-tools/blob/kubernetes/README-PRODUCTION.md)
* [AWS EC2 Docker Deployment](https://github.com/spdx/spdx-online-tools/blob/deploy-aws-ec2/README-PRODUCTION.md)

We should move the PR documentation into a README.

@rnjudge Thanks for reviewing - feedback welcome!

**Comment by goneall** [comment]
Note: Sandbox IP changed (comment above has also been corrected): http://52.32.53.255/app/

**Comment by goneall** [comment]
This has now been fully deployed 👍
